# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myMovies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for myMovies
  pod 'Alamofire', '~> 4.8.2'

  target 'myMoviesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
